import time, random
from definitions import *

def get_friends(user_self):
	return [
		User(1,"Will",19,"Boston",["williamsaulnier.com"],[],[]),
		User(2,"Jeff",19,"New York",["jefftao.com"],[],[]),
		]

def get_recent_posts(user_self, age_fish):
	return [
		Post(0,0,"Just ate a sandwich, LOL0 testing the line wrapping also so this text should be enough to cause wrap, but I don't have an elegant fallback for wrapping", "feeling full", [0]),
		Post(1,1,"Just ate a sandwich, LOL1", "feeling full", [1,2,3])]

def get_comment_by_id(user_self, comment_id):
		return Comment(comment_id,0,"autogenerated_comment_id_%i"%(comment_id))


def get_user_by_id(uid):
	return User(random.randint(3,1000),"RandomUser",19,"universe",[],[],[])

def add_friend(friend, user_self):
	time.sleep(0.5)
	return True

def post_comment(comment, user_self, commentbody):
	return True

def get_online_friends(user_self):
	return [1]
